### ISSUE TITLE
error while deploying firebase backend (subscription example ClassyTaxi)

### ISSUE THREAD

**Issue by JenyaKirmizaTripTop** [android/play-billing-samples#191]
I've tried to deploy the node backend code to firebase using the instruction in tutorial. Though i'm receiving following error

```
Detailed stack trace: /user_code/node_modules/googleapis/node_modules/gaxios/build/src/index.js:28
async function request(opts) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/googleapis/node_modules/gtoken/build/src/index.js:18:18)

```
Unfortunately, I'm not familiar with node js. Can you help, please?

```
node -v
v10.15.3
```

`typescript@2.5.3 `

**Comment by calren** [comment]
@JenyaKirmizaTripTop there's been some updates to the firebase server. feel free to give this another try and open an issue if you run into any issues!
