### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference

### ISSUE THREAD

**Issue by dddddl** [android/play-billing-samples#248]
2019-11-13 10:42:39.246 32270-32270/com.auntec.photo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.auntec.photo, PID: 32270
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.auntec.photo/com.android.billingclient.api.ProxyBillingActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2971)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6738)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
        at android.os.Parcel.readException(Parcel.java:2019)
        at android.os.Parcel.readException(Parcel.java:1959)
        at android.app.IActivityManager$Stub$Proxy.startActivityIntentSender(IActivityManager.java:6555)
        at android.app.Activity.startIntentSenderForResultInner(Activity.java:4833)
        at android.app.Activity.startIntentSenderForResult(Activity.java:4809)
        at android.app.Activity.startIntentSenderForResult(Activity.java:4776)
        at com.android.billingclient.api.ProxyBillingActivity.onCreate(ProxyBillingActivity.java:47)
        at android.app.Activity.performCreate(Activity.java:7113)
        at android.app.Activity.performCreate(Activity.java:7104)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2846)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2971) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:6738) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)

**Comment by dddddl** [comment]
i got this error when i call the launchBillingFlow method

**Comment by calren** [comment]
Hey @dddddl  , issues filed on this repo should ideally be related to the samples in this repo. Since this is a more generic question, I'm going to go ahead and close it for now. Feel free to ask questions on stackoverflow with the tag android-billing! That might get more traction and attention for generic Android billing issues than filing issues here. Thanks!
