### ISSUE TITLE
TrivialDriveKotlin crash on launch in Pixel 3 XL API 28 emulator

### ISSUE THREAD

**Issue by Deracination** [android/play-billing-samples#290]
The TrivialDriveKotlin README says the application can be run 'as-is' but the app immediately crashes on startup. This is running with Android Studio 3.6.1 on hyper-v emulator for Pixel 3 XL, API 28 with Google APIs (details in attached file).

```
/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.subscriptions.classytaxi, PID: 4858
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.subscriptions.classytaxi/com.example.subscriptions.ui.MainActivity}: java.lang.IllegalArgumentException: Given String is empty or null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: Given String is empty or null
        at com.google.android.gms.common.internal.zzbq.zzgv(Unknown Source:11)
        at com.google.android.gms.internal.zzebe.<init>(Unknown Source:3)
        at com.google.firebase.auth.FirebaseAuth.<init>(Unknown Source:10)
        at com.google.firebase.auth.internal.zzj.<init>(Unknown Source:0)
        at com.google.firebase.auth.FirebaseAuth.zzb(Unknown Source:19)
        at com.google.firebase.auth.FirebaseAuth.getInstance(Unknown Source:4)
        at com.example.subscriptions.ui.FirebaseUserViewModel.updateFirebaseUser(FirebaseUserViewModel.kt:51)
        at com.example.subscriptions.ui.FirebaseUserViewModel.<init>(FirebaseUserViewModel.kt:44)
        at java.lang.Class.newInstance(Native Method)
        at android.arch.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:151)
        at android.arch.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:210)
        at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:134)
        at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:102)
        at com.example.subscriptions.ui.MainActivity.onCreate(MainActivity.kt:86)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```
[avd_details.txt](https://github.com/android/play-billing-samples/files/4406872/avd_details.txt)

**Comment by calren** [comment]
Hey @Deracination , I'm unable to reproduce this issue. I was able to download the code from this repository and run the code as-is. 

I suspect this might be a problem if you're running the app on an emulator that doesn't have the play store installed.

**Comment by ArcherLucky** [comment]
I'm running TaxiAppKotlin on physical machines(Pixel 3), and have same problem
