### ISSUE TITLE
has already been added to the window manager

### ISSUE THREAD

**Issue by rainmeterLotus** [android/play-billing-samples#298]
> 
04-16 12:32:43.860 V/PhoneWindow(28174): DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@2092b89[]
04-16 12:32:43.863 D/ViewRootImpl[aaf](28174): hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
04-16 12:32:43.869 V/PhoneWindow(28174): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@55d8bbc, this = DecorView@2092b89[aaf]
04-16 12:32:44.338 V/PhoneWindow(28174): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@211f8e9, this = DecorView@6b95d22[aag]
04-16 12:32:44.854 W/System  (28174): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
04-16 12:32:44.855 I/System.out(28174): e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
04-16 12:32:45.738 D/OpenSSLLib(28174): OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
04-16 12:32:45.740 D/OpenSSLLib(28174): OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object
04-16 12:32:46.333 W/ActivityThread(28174): handleWindowVisibility: no activity for token android.os.BinderProxy@b4d4ce4
04-16 12:32:46.443 V/PhoneWindow(28174): DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@c70f105[]
04-16 12:32:46.445 D/ViewRootImpl[ProxyBillingActivity](28174): hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
04-16 12:32:46.452 V/PhoneWindow(28174): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@34f3c68, this = DecorView@c70f105[ProxyBillingActivity]
04-16 12:32:48.953 W/ProxyBillingActivity(28174): Activity finished with resultCode 0 and billing's responseCode: 1
04-16 12:32:49.120 W/BillingHelper(28174): Couldn't find purchase lists, trying to find single data.
04-16 12:32:49.120 W/BillingHelper(28174): Received a bad purchase data.
04-16 12:32:49.121 W/BillingHelper(28174): Couldn't find single purchase data as well.
04-16 12:32:49.242 V/PhoneWindow(28174): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@55d8bbc, this = DecorView@2092b89[aaf]
04-16 12:32:49.252 D/AndroidRuntime(28174): Shutting down VM
--------- beginning of crash
04-16 12:32:49.253 E/AndroidRuntime(28174): FATAL EXCEPTION: main
04-16 12:32:49.253 E/AndroidRuntime(28174): java.lang.IllegalStateException: View android.widget.LinearLayout{d451eb9 V.E...... ......ID 0,0-428,75} has already been added to the window manager.
04-16 12:32:49.253 E/AndroidRuntime(28174): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:328)
04-16 12:32:49.253 E/AndroidRuntime(28174): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
04-16 12:32:49.253 E/AndroidRuntime(28174): 	at android.widget.Toast$TN.handleShow(Toast.java:499)
04-16 12:32:49.253 E/AndroidRuntime(28174): 	at android.widget.Toast$TN$1.handleMessage(Toast.java:403)
04-16 12:32:49.253 E/AndroidRuntime(28174): 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-16 12:32:49.253 E/AndroidRuntime(28174): 	at android.os.Looper.loop(Looper.java:193)
04-16 12:32:49.253 E/AndroidRuntime(28174): 	at android.app.ActivityThread.main(ActivityThread.java:6746)
04-16 12:32:49.253 E/AndroidRuntime(28174): 	at java.lang.reflect.Method.invoke(Native Method)
04-16 12:32:49.253 E/AndroidRuntime(28174): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-16 12:32:49.253 E/AndroidRuntime(28174): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
04-16 12:32:49.316 E/hera.process(28174): CRASH LOG START...
04-16 12:32:49.316 E/hera.process(28174): {STACK_TRACE=2
04-16 12:32:49.316 E/hera.process(28174): java.lang.IllegalStateException: View android.widget.LinearLayout{d451eb9 V.E...... ......ID 0,0-428,75} has already been added to the window manager.
04-16 12:32:49.316 E/hera.process(28174): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:328)
04-16 12:32:49.316 E/hera.process(28174): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
04-16 12:32:49.316 E/hera.process(28174): 	at android.widget.Toast$TN.handleShow(Toast.java:499)
04-16 12:32:49.316 E/hera.process(28174): 	at android.widget.Toast$TN$1.handleMessage(Toast.java:403)
04-16 12:32:49.316 E/hera.process(28174): 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-16 12:32:49.316 E/hera.process(28174): 	at android.os.Looper.loop(Looper.java:193)
04-16 12:32:49.316 E/hera.process(28174): 	at android.app.ActivityThread.main(ActivityThread.java:6746)
04-16 12:32:49.316 E/hera.process(28174): 	at java.lang.reflect.Method.invoke(Native Method)
04-16 12:32:49.316 E/hera.process(28174): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-16 12:32:49.316 E/hera.process(28174): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
04-16 12:32:49.345 D/OpenSSLLib(28174): OpensslErr:Module:12(177:); file:external/boringssl/src/crypto/asn1/asn1_lib.c ;Line:168;Function:ASN1_get_object

it`s maybe ProxyBillingActivity bug??

**Comment by calren** [comment]
Hey @rainmeterLotus , looking at the stack trace, it's a bit hard to tell what the issue was here. Did you experience a crash? Was this the result of running one of the sample apps?

**Comment by rainmeterLotus** [comment]
> Hey @rainmeterLotus , looking at the stack trace, it's a bit hard to tell what the issue was here. Did you experience a crash? Was this the result of running one of the sample apps?

These logs come from the background of our company, which is the only one that is not easy to reproduce

**Comment by calren** [comment]
Not seeing anything in the stacktrace that indicates this is related to the Play Billing Library, so I'm going to go ahead and close this issue for now.
