### ISSUE TITLE
App started to crash on server side

### ISSUE THREAD

**Issue by vafaminato** [android/play-billing-samples#300]
Everything was fine. Now when I try to open the classytaxijava app, the app crashes before login (phone is online or offline). Firebases records some errors:

```
{ OtherError: The current user has insufficient permissions to perform the requested operation.
    at PurchaseManager.convertPlayAPIErrorToLibraryError (/srv/lib/play-billing/PurchasesManager.js:336:30)
    at playDeveloperApiClient.purchases.subscriptions.get (/srv/lib/play-billing/PurchasesManager.js:122:37)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7) name: 'OtherError' }
```
And also the error below:

```
{ OtherError: The current user has insufficient permissions to perform the requested operation.
    at PurchaseManager.convertPlayAPIErrorToLibraryError (/srv/lib/play-billing/PurchasesManager.js:336:30)
    at playDeveloperApiClient.purchases.subscriptions.get (/srv/lib/play-billing/PurchasesManager.js:122:37)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7) name: 'OtherError' }
```

**Comment by vafaminato** [comment]
Any suggestion with this crash? I still couldn't solve this.

**Comment by vafaminato** [comment]
There seem to be another issue. First user subscribes for premium plan. Then cancel the subscription. logging out and logging in again does not show the change (still is as premium). So, you have to use the refresh button on top right. Then it finds out you are no longer premium. But, it just let you subscribe in basic pan. When you try to be premium again, it shows the play store subscription (although there is empty and you are not subscribed to anything).

**Comment by spiraldevapps** [comment]
Hey Did you finally solve this issue? @vafaminato

**Comment by vafaminato** [comment]
> Hey Did you finally solve this issue? @vafaminato

Yes. But it is not the permanent solution.
For `erverError error = serverErrorFromFirebaseException(task.getException());`, you add a if-else statement to check if `error` is null or not. If null, do nothing, else ...

For the second issue, I'm not really sure. Sometimes it works sometimes it doesn't. You have to trigger the refresh in different cases (like every time that user presses the fragment tabs...).
