### ISSUE TITLE
arm64-v8 crash on boot！

### ISSUE THREAD

**Issue by JoneJay** [android/play-billing-samples#435]

**Comment by JoneJay** [comment]
stack:
java.lang.IllegalArgumentException: Given String is empty or null 
 at 
com.google.android.gms.common.internal.zzbq.zzgv
......
MainActivity.kt:210

**Comment by JoneJay** [comment]
W/System.err: java.lang.IllegalArgumentException: Given String is empty or null
        at com.google.android.gms.common.internal.zzbq.zzgv(Unknown Source:11)
        at com.google.android.gms.auth.api.signin.GoogleSignInOptions$Builder.zzfc(Unknown Source:0)
        at com.google.android.gms.auth.api.signin.GoogleSignInOptions$Builder.requestIdToken(Unknown Source:3)
        at com.firebase.ui.auth.AuthUI$IdpConfig$GoogleBuilder.setSignInOptions(AuthUI.java:754)
W/System.err:     at com.firebase.ui.auth.AuthUI$IdpConfig$GoogleBuilder.setScopes(AuthUI.java:738)
        at com.firebase.ui.auth.AuthUI$IdpConfig$GoogleBuilder.build(AuthUI.java:766)
        at com.example.subscriptions.ui.MainActivity.triggerSignIn(MainActivity.kt:211)
        at com.example.subscriptions.ui.MainActivity.onOptionsItemSelected(MainActivity.kt:187)
        at android.app.Activity.onMenuItemSelected(Activity.java:3608)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:436)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:196)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
W/System.err:     at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:204)
        at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
W/System.err:     at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25921)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6878)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
