### ISSUE TITLE
Google Play Billing 4.0.0 NPE

### ISSUE THREAD

**Issue by TeGlobal** [android/play-billing-samples#484]
I'm using billing library version 4.0.0 suddenly my app crashes.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ta5sees.sambateek, PID: 9214
    java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter args
        at com.facebook.appevents.iap.InAppPurchaseBillingClientWrapper$BillingClientStateListenerWrapper.invoke(Unknown Source:12)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy3.onBillingServiceDisconnected(Unknown Source)
        at com.android.billingclient.api.zzaf.onServiceDisconnected(com.android.billingclient:billing@@4.0.0:4)
        at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:2103)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2118)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8587)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by TeGlobal** [comment]
??

**Comment by Luckeee** [comment]
https://github.com/facebook/facebook-sdk-for-unity/issues/579
here

**Comment by TeGlobal** [comment]
Sorry I thought the issue in Google play billing library but it's in Facebook SDK based on @Luckeee comment.
I'm closing the issue.
