### ISSUE TITLE
java.lang.IllegalArgumentException: Given String is empty or null

### ISSUE THREAD

**Issue by KumarVelu** [android/play-billing-samples#488]
Crash when running 'ClassyTaxiAppKotlin'. 

com.example.subscriptions.classytaxi E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.subscriptions.classytaxi, PID: 11632
    java.lang.IllegalArgumentException: Given String is empty or null
        at com.google.android.gms.common.internal.zzbq.zzgv(Unknown Source:11)
        at com.google.android.gms.auth.api.signin.GoogleSignInOptions$Builder.zzfc(Unknown Source:0)
        at com.google.android.gms.auth.api.signin.GoogleSignInOptions$Builder.requestIdToken(Unknown Source:3)
        at com.firebase.ui.auth.AuthUI$IdpConfig$GoogleBuilder.setSignInOptions(AuthUI.java:754)
        at com.firebase.ui.auth.AuthUI$IdpConfig$GoogleBuilder.setScopes(AuthUI.java:738)
        at com.firebase.ui.auth.AuthUI$IdpConfig$GoogleBuilder.build(AuthUI.java:766)
        at com.example.subscriptions.ui.MainActivity.triggerSignIn(MainActivity.kt:210)
        at com.example.subscriptions.ui.MainActivity.access$triggerSignIn(MainActivity.kt:54)
        at com.example.subscriptions.ui.MainActivity$onCreate$4.onChanged(MainActivity.kt:128)
        at com.example.subscriptions.ui.MainActivity$onCreate$4.onChanged(MainActivity.kt:54)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at android.arch.lifecycle.LiveData$1.run(LiveData.java:87)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by liyirui-git** [comment]
Same problem.

**Comment by liyirui-git** [comment]
But you may take a look at this https://github.com/android/play-billing-samples/tree/master/ClassyTaxiJava#what-do-i-need first to make sure you have already set up all the things this project needed. I'm looking into it now.
