### ISSUE TITLE
Too many bind requests(999+) for service Intent

### ISSUE THREAD

**Issue by thevinhhuynh** [android/play-billing-samples#641]
I'm using BILLING: 6.0.0, I encountered the above error. The devices are mainly Samsung

java.lang.IllegalStateException: Too many bind requests(999+) for service Intent { act=com.android.vending.billing.InAppBillingService.BIND pkg=com.android.vending cmp=com.android.vending/com.google.android.finsky.billing.iab.InAppBillingService (has extras) }
  at android.app.ContextImpl.bindServiceCommon (ContextImpl.java:2115)
  at android.app.ContextImpl.bindService (ContextImpl.java:2024)

Help me!

**Comment by leCandas** [comment]
Exactly same issue  with some Samsung devices with billing 6.0.1

Fatal Exception: java.lang.IllegalStateException: Too many bind requests(999+) for service Intent { act=com.android.vending.billing.InAppBillingService.BIND pkg=com.android.vending cmp=com.android.vending/com.google.android.finsky.billing.iab.InAppBillingService (has extras) }
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2115)
       at android.app.ContextImpl.bindService(ContextImpl.java:2024)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:870)
       at com.android.billingclient.api.BillingClientImpl.startConnection(com.android.billingclient:billing@@6.0.1:64)

**Comment by Zachary625** [comment]
same here with PBL 5.0.0 this seems to be Samsung Android 13 bug but still hope we can get some insights

**Comment by JRWilding** [comment]
100% Samsung on Android 13 (from an app with 10m+ installs)

**Comment by leCandas** [comment]
I had the same issue, only coming from Samsung devices.

Since I want to address this quickly.
I have surrounded the billingClient.startConnection(this); with a try catch block.
When I get an exception I just end the connection billingClient.endConnection(); billingClient = null;
And posting a delayed call to a handler to re-initilize the billingClient.

This approach will at least address the crash.

**Comment by kolagit** [comment]
Same issue using PBL 5.0!
Any updates???

**Comment by congdanh1608** [comment]
Any updates.
I don't know why I got many crashes from one app, but others did not.
I tried to downgrade the in-app billing SDK version, but it is not working.

**Comment by igorwojda** [comment]
Issue seems to be occurring on Samsung devices running Android 13 (mostly while app is in background). Reference:
- https://stackoverflow.com/questions/76512231/do-samsung-phones-running-android-13-have-an-intent-bug
- https://community.revenuecat.com/sdks-51/how-to-fix-crash-too-many-bind-requests-999-for-service-intent-inappbillingservice-3317
- https://forum.developer.samsung.com/t/illegalstateexception-too-many-bind-requests-999-for-service-inte/28242

**Comment by npkhung92** [comment]
I am also using billingclient version 6.0.1 and faced the same issue. Is there any updates on this?

**Comment by ErickSorto** [comment]
I am having the same issue.

**Comment by igorwojda** [comment]
Workaround - make sure that `billingClient.startConnection()` is called only when app is in foreground
