### ISSUE TITLE
SecurityException: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by ZouZLong** [android/play-billing-samples#644]
I am using the latest settlement version 6.0.1, but this problem still occurs

**Comment by ZouZLong** [comment]
This problem still exists on the Adroid14 version

**Comment by ZouZLong** [comment]
17410-21 23:25:41.042 22825 22953 E AndroidRuntime: FATAL EXCEPTION: pool-6-thread-3
--
17510-21 23:25:41.042 22825 22953 E AndroidRuntime: Process: cellmate.qiui.com, PID: 22825
17610-21 23:25:41.042 22825 22953 E AndroidRuntime: java.lang.SecurityException: cellmate.qiui.com: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
17710-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
17810-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.os.Parcel.createException(Parcel.java:3041)
17910-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.os.Parcel.readException(Parcel.java:3024)
18010-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.os.Parcel.readException(Parcel.java:2966)
18110-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
18210-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
18310-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
18410-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
18510-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
18610-21 23:25:41.042 22825 22953 E AndroidRuntime: at com.hyphenate.chat.core.EMAdvanceDebugManager.h(Unknown Source:21)
18710-21 23:25:41.042 22825 22953 E AndroidRuntime: at com.hyphenate.chat.core.EMAdvanceDebugManager.a(Unknown Source:4)
18810-21 23:25:41.042 22825 22953 E AndroidRuntime: at com.hyphenate.chat.EMClient.onNewLogin(Unknown Source:39)
18910-21 23:25:41.042 22825 22953 E AndroidRuntime: at com.hyphenate.chat.EMClient$8.run(Unknown Source:158)
19010-21 23:25:41.042 22825 22953 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
19110-21 23:25:41.042 22825 22953 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
19210-21 23:25:41.042 22825 22953 E AndroidRuntime: at java.lang.Thread.run(Thread.java:1012)
19310-21 23:25:41.042 22825 22953 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
19410-21 23:25:41.042 22825 22953 E AndroidRuntime: at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13908)
19510-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
19610-21 23:25:41.042 22825 22953 E AndroidRuntime: at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
19710-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.os.Binder.execTransactInternal(Binder.java:1339)
19810-21 23:25:41.042 22825 22953 E AndroidRuntime: at android.os.Binder.execTransact(Binder.java:1275)
19910-21 23:25:41.042 22825 22953 E AndroidRuntime:
20010-21 23:25:41.043 22825 22953 E CrashReport: Java Crash Happen cause by pool-6-thread-3(111)
